apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
  namespace: devsecops-prod # FIX (KSV-0110): Set explicit non-default namespace
  labels:
    app: devsecops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001 # FIX (KSV-0020): Set UID > 10000
        runAsGroup: 10001 # FIX (KSV-0021): Set GID > 10000
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault # FIX (KSV-0030 & KSV-0104): Set seccomp profile
      containers:
        - name: web
          image: docker.io/library/devsecops-app:v1.0.0 # FIX (KSV-0125): Explicit registry domain
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5